version: '3.1'
services:
  redis:
    restart: always
    image: daocloud.io/library/redis:5.0.7
    container_name: redis
    ports:
      - "6379:6379"
  elasticsearch:
    image: daocloud.io/library/elasticsearch:7.4.2
    restart: always
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /opt/docker_elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /opt/docker_elasticsearch/data:/usr/share/elasticsearch/data
      - /opt/docker_elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: daocloud.io/library/kibana:7.4.2
    restart: always
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - elasticsearch_url=http://192.168.174.128:9200
    depends_on:
      - elasticsearch